name: soteria
description: "Soteria - Competitive Learning Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: any
  flutter_screenutil: any
  google_fonts: any
  flutter_svg: any
  cached_network_image: any
  intl: any
  shared_preferences: any
  connectivity_plus: any
  flutter_dotenv: any
  package_info_plus: any
  device_info_plus: any
  logger: any
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: any
  local_auth: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/fonts/
    - assets/json/

    - .env.dev
    - .env.prod