// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/auth/auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:soteria/core/models/result.dart' as _i4;
import 'package:soteria/features/auth/domain/entities/auth_provider_type.dart'
    as _i8;
import 'package:soteria/features/auth/domain/entities/auth_session.dart' as _i7;
import 'package:soteria/features/auth/domain/entities/auth_user.dart' as _i5;
import 'package:soteria/features/auth/domain/entities/session.dart' as _i9;
import 'package:soteria/features/auth/domain/repositories/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i2.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> signIn({
    required String? email,
    required String? password,
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
              #rememberMe: rememberMe,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                  #rememberMe: rememberMe,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> register({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #username: username,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> signInWithPhone(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhone, [phoneNumber]),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#signInWithPhone, [phoneNumber]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> signInWithBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithBiometrics, []),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#signInWithBiometrics, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> signInAsGuest() =>
      (super.noSuchMethod(
            Invocation.method(#signInAsGuest, []),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#signInAsGuest, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i7.AuthSession>> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue: _i3.Future<_i4.Result<_i7.AuthSession>>.value(
              _i6.dummyValue<_i4.Result<_i7.AuthSession>>(
                this,
                Invocation.method(#refreshSession, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.AuthSession>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser?>> currentUser() =>
      (super.noSuchMethod(
            Invocation.method(#currentUser, []),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser?>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser?>>(
                this,
                Invocation.method(#currentUser, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser?>>);

  @override
  _i3.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Result<void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> updateProfile({
    String? username,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #username: username,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#updateProfile, [], {
                  #username: username,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<bool>> checkUsernameAvailability(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#checkUsernameAvailability, [username]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#checkUsernameAvailability, [username]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<void>> linkProvider(_i8.AuthProviderType? type) =>
      (super.noSuchMethod(
            Invocation.method(#linkProvider, [type]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#linkProvider, [type]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> unlinkProvider(_i8.AuthProviderType? type) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkProvider, [type]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#unlinkProvider, [type]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> migrateGuestData() =>
      (super.noSuchMethod(
            Invocation.method(#migrateGuestData, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#migrateGuestData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i9.Session?>> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i3.Future<_i4.Result<_i9.Session?>>.value(
              _i6.dummyValue<_i4.Result<_i9.Session?>>(
                this,
                Invocation.method(#restoreSession, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.Session?>>);

  @override
  _i3.Future<_i4.Result<void>> persistSession(_i9.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#persistSession, [session]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#persistSession, [session]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#clearSession, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<bool> isSessionValid() =>
      (super.noSuchMethod(
            Invocation.method(#isSessionValid, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Result<_i5.AuthUser>> upgradeGuestSession({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeGuestSession, [], {
              #email: email,
              #password: password,
              #username: username,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.AuthUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthUser>>(
                this,
                Invocation.method(#upgradeGuestSession, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthUser>>);

  @override
  _i3.Future<_i4.Result<void>> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [email]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#requestPasswordReset, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> verifyRecoveryCode({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyRecoveryCode, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#verifyRecoveryCode, [], {
                  #email: email,
                  #code: code,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> resetPassword({
    required String? email,
    required String? newPassword,
    required String? verificationCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
              #verificationCode: verificationCode,
            }),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#resetPassword, [], {
                  #email: email,
                  #newPassword: newPassword,
                  #verificationCode: verificationCode,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> resendRecoveryCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendRecoveryCode, [email]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#resendRecoveryCode, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
